#pragma once

#include "src/include/background.h"
#include "src/include/camera.h"
#include "src/include/component.h"
#include "src/include/game_object.h"
#include "src/include/image.h"
#include "src/include/lights.h"
#include "src/include/material.h"
#include "src/include/mesh.h"
#include "src/include/mesh_renderer.h"
#include "src/include/model.h"
#include "src/include/model_renderer.h"
#include "src/include/OBJ_Loader.h"
#include "src/include/shader.h"
#include "src/include/skybox.h"
#include "src/include/stb_image.h"
#include "src/include/stb_image_write.h"
#include "src/include/texture.h"
#include "src/include/transform.h"
#include "src/include/user_camera.h"
#include "src/include/utils.h"
#include "src/include/window.h"
#include "src/include/input.h"

namespace PG = Progression;
